### ISSUE TITLE
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated

### ISSUE THREAD

**Issue by chmduquesne** [Oefenweb/ansible-dnsmasq#8]
Hi,

Thank you for this role! I am loving how simple it is to use it and how flexible it is. Unfortunately, I am getting the following warning when using it and I would love if this kept working in the future:

    TASK [oefenweb.dnsmasq : install dependencies] ********************************************************************************************************************************************************
    [DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `name: "{{ item }}"`, please use 
    `name: '{{ dnsmasq_dependencies }}'` and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

Is there a way to fix this in a future version?

All the best,
Christophe-Marie

**Comment by tersmitten** [comment]
Fixed in https://github.com/Oefenweb/ansible-dnsmasq/releases/tag/v2.2.10
