### ISSUE TITLE
Option to set as default resolver

### ISSUE THREAD

**Issue by alanmcg** [Oefenweb/ansible-dnsmasq#9]
I have a chicken and egg situation where systemd.resolved needs to be disabled before running this role, but doing so stops it from being able to apt install dnsmasq (repo fails to resolve).

It would be nice to have the role take care of this:

1. install dnsmasq
2. disable systemd.resolved
3. (re)start dnsmasq

**Comment by tersmitten** [comment]
Is [this](#10) useful to you?

**Comment by tersmitten** [comment]
https://github.com/Oefenweb/ansible-dnsmasq/pull/10/files#diff-3d0ff1709ca48add100327bb2a468e6c508fb92a159c64c4f99ad1df89d9bddeR63

**Comment by tersmitten** [comment]
https://github.com/Oefenweb/ansible-dnsmasq/pull/10/files#diff-4e252bec2e4d78bea6a0d1c30dce27d502d65fda967ee2b4e1c125c1f9e3d65bR3

**Comment by tersmitten** [comment]
Feel free to reopen if not
